name: publish

on:
  push:
    branches:
      - main

# from https://actuated.dev/blog/multi-arch-docker-github-actions
jobs:
  publish:
     permissions:
       packages: write

-   runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Release build
        id: release_build
        uses: docker/build-push-action@v4
        with:
          outputs: "type=registry,push=true"
          provenance: false
          platforms: linux/amd64,linux/arm/v6,linux/arm64
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/multilspy-java-docker:${{ github.sha }}
            ghcr.io/${{ env.REPO_OWNER }}/multilspy-java-docker:latest